server:
  port: 8092

#jsp setting
spring:
  mvc:
    view:
      prefix: /WEB-INF/
      suffix: .jsp

#mysql setting ()
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://db-324obg-kr.vpc-pub-cdb.ntruss.com:3306/studydb?serverTimezone=Asia/Seoul
    username: study
    password: bitcamp!@#123

  mybatis:
    configuration:
      log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

logging:
  level:
    org.mybatis: DEBUG
    org.apache.ibatis: DEBUG

#mybatis setting
mybatis:
  type-aliases-package: data.dto
  mapper-locations:
  - /mapper/**/*.xml